/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e93b46ed1a1284ed1c85502da53b42e0)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "OrchestratorAgent";
	}
	interface Env {
		AI: Ai;
		OrchestratorAgent: DurableObjectNamespace<import("./src/server").OrchestratorAgent>;
	}
}
interface Env extends Cloudflare.Env {}
